version: '3.8'

services:
  api:
    container_name: api
    build: webapp
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./webapp/app:/app
    ports:
      - 8000:8000
    environment:
      - LOG_LEVEL=warning
  
  web:
    container_name: nginx
    restart: always
    build: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api